import type { Metadata } from 'next'
import { Chakra_Petch } from 'next/font/google'
import './globals.css'
import Sidebar from './components/Sidebar'
import { NavbarAdminContextProvider } from '@/contexts/useNavbarAdmin'
import NavbarWrapper from './components/NavbarWrapper'

const chakraPetch = Chakra_Petch({
  subsets: ['thai'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${chakraPetch.className} antialiased`}>
        
        <NavbarWrapper>
          {children}
        </NavbarWrapper>
      </body>
    </html>
  )
}
