import type { Metadata } from 'next'
import { Chakra_Petch } from 'next/font/google'
import './globals.css'
import Sidebar from './components/Sidebar'
import { NavbarAdminContextProvider } from '@/contexts/useNavbarAdmin'

const chakraPetch = Chakra_Petch({
  subsets: ['thai'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${chakraPetch.className} antialiased`}>
        <div className="flex h-screen">
          <Sidebar />
          <div className="flex flex-1 flex-col">
            <NavbarAdminContextProvider>
              <div className="min-h-0 flex-1 overflow-auto to-white">{children}</div>
            </NavbarAdminContextProvider>
            <nav className="bg-green-500">footer</nav>
          </div>
        </div>
      </body>
    </html>
  )
}
